# Generated by Django 5.2.12 on 2026-03-25 00:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('zip', 'ZIP'), ('git', 'Git')], max_length=12)),
                ('repository_url', models.URLField(blank=True)),
                ('archive', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('analyzing', 'Analyzing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('detected_language', models.CharField(blank=True, max_length=64)),
                ('detected_framework', models.CharField(blank=True, max_length=64)),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('execution_root', models.CharField(blank=True, max_length=255)),
                ('package_manager', models.CharField(blank=True, max_length=64)),
                ('install_command', models.CharField(blank=True, max_length=255)),
                ('build_command', models.CharField(blank=True, max_length=255)),
                ('start_command', models.CharField(blank=True, max_length=255)),
                ('probable_ports', models.JSONField(blank=True, default=list)),
                ('environment_variables', models.JSONField(blank=True, default=list)),
                ('services', models.JSONField(blank=True, default=list)),
                ('found_files', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('analysis_payload', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('dockerfile', 'Dockerfile'), ('compose', 'Docker Compose'), ('ignore', 'Docker Ignore'), ('guide', 'Guide')], max_length=32)),
                ('path', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='core.projectanalysis')),
            ],
            options={
                'ordering': ['path'],
                'constraints': [models.UniqueConstraint(fields=('analysis', 'path'), name='unique_generated_artifact_per_analysis')],
            },
        ),
    ]
