# Generated by Django 5.2.12 on 2026-03-25 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectanalysis',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectanalysis',
            name='job_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='projectanalysis',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_analyses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectanalysis',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectanalysis',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('analyzing', 'Analyzing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='queued', max_length=16),
        ),
    ]
