# Generated by Django 5.2.12 on 2026-03-25 05:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_projectanalysis_finished_at_projectanalysis_job_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectanalysis',
            name='generation_profile',
            field=models.CharField(choices=[('production', 'Production'), ('development', 'Development')], default='production', max_length=16),
        ),
        migrations.AddField(
            model_name='projectanalysis',
            name='source_commit',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='ExecutionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('validation', 'Validation'), ('github_pr', 'GitHub PR'), ('preview', 'Preview')], max_length=24)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('ready', 'Ready'), ('failed', 'Failed'), ('canceled', 'Canceled')], db_index=True, default='queued', max_length=16)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('result_payload', models.JSONField(blank=True, default=dict)),
                ('logs', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='execution_jobs', to='core.projectanalysis')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PreviewRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('ready', 'Ready'), ('failed', 'Failed'), ('stopped', 'Stopped')], db_index=True, default='queued', max_length=16)),
                ('runtime_kind', models.CharField(blank=True, choices=[('compose', 'Compose'), ('container', 'Container')], max_length=16)),
                ('workspace_path', models.CharField(blank=True, max_length=1024)),
                ('workspace_root', models.CharField(blank=True, max_length=1024)),
                ('command', models.CharField(blank=True, max_length=512)),
                ('access_url', models.URLField(blank=True)),
                ('ports', models.JSONField(blank=True, default=dict)),
                ('resource_names', models.JSONField(blank=True, default=list)),
                ('logs', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preview_runs', to='core.projectanalysis')),
                ('execution_job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preview_run', to='core.executionjob')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preview_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtifactSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('event', models.CharField(choices=[('generation', 'Generation'), ('edit', 'Edit')], max_length=16)),
                ('generation_profile', models.CharField(choices=[('production', 'Production'), ('development', 'Development')], max_length=16)),
                ('kind', models.CharField(choices=[('dockerfile', 'Dockerfile'), ('compose', 'Docker Compose'), ('ignore', 'Docker Ignore'), ('guide', 'Guide')], max_length=32)),
                ('path', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifact_snapshots', to='core.projectanalysis')),
            ],
            options={
                'ordering': ['-version', 'path'],
                'constraints': [models.UniqueConstraint(fields=('analysis', 'version', 'path'), name='unique_artifact_snapshot_per_version')],
            },
        ),
        migrations.CreateModel(
            name='ExternalRepoConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('github', 'GitHub')], default='github', max_length=24)),
                ('label', models.CharField(max_length=120)),
                ('account_name', models.CharField(blank=True, max_length=255)),
                ('access_token', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_repo_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['label'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'provider', 'label'), name='unique_repo_connection_label_per_owner')],
            },
        ),
    ]
