# Generated by Django 5.2.12 on 2026-03-25 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_projectanalysis_generation_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifactsnapshot',
            name='generation_profile',
            field=models.CharField(choices=[('production', 'Production'), ('development', 'Development'), ('ci', 'CI')], max_length=16),
        ),
        migrations.AlterField(
            model_name='projectanalysis',
            name='generation_profile',
            field=models.CharField(choices=[('production', 'Production'), ('development', 'Development'), ('ci', 'CI')], default='production', max_length=16),
        ),
    ]
