# Generated by Django 5.2.12 on 2026-03-26 00:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify


def backfill_workspaces(apps, schema_editor):
    Workspace = apps.get_model("core", "Workspace")
    WorkspaceMembership = apps.get_model("core", "WorkspaceMembership")
    ProjectAnalysis = apps.get_model("core", "ProjectAnalysis")
    User = apps.get_model(*settings.AUTH_USER_MODEL.split("."))

    def unique_slug(base):
        root = slugify(base) or "workspace"
        slug = root
        index = 2
        while Workspace.objects.filter(slug=slug).exists():
            slug = f"{root}-{index}"
            index += 1
        return slug

    for user in User.objects.all():
        username = getattr(user, "username", "") or str(user.pk)
        workspace = (
            Workspace.objects.filter(owner=user)
            .order_by("created_at")
            .first()
        )
        if workspace is None:
            workspace = Workspace.objects.create(
                owner=user,
                name=f"{username} workspace",
                slug=unique_slug(f"{username}-workspace"),
                description="Workspace personal de AutoDocker.",
                visibility="private",
            )
        WorkspaceMembership.objects.update_or_create(
            workspace=workspace,
            user=user,
            defaults={"role": "owner"},
        )
        ProjectAnalysis.objects.filter(owner=user, workspace__isnull=True).update(workspace=workspace)


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_artifactsnapshot_generation_profile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectanalysis',
            name='cicd_report',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='projectanalysis',
            name='deploy_report',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='projectanalysis',
            name='healthcheck_report',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='projectanalysis',
            name='security_report',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='artifactsnapshot',
            name='kind',
            field=models.CharField(choices=[('dockerfile', 'Dockerfile'), ('compose', 'Docker Compose'), ('ignore', 'Docker Ignore'), ('guide', 'Guide'), ('pipeline', 'Pipeline'), ('deploy', 'Deploy')], max_length=32),
        ),
        migrations.AlterField(
            model_name='generatedartifact',
            name='kind',
            field=models.CharField(choices=[('dockerfile', 'Dockerfile'), ('compose', 'Docker Compose'), ('ignore', 'Docker Ignore'), ('guide', 'Guide'), ('pipeline', 'Pipeline'), ('deploy', 'Deploy')], max_length=32),
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('team', 'Team')], default='private', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='projectanalysis',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='core.workspace'),
        ),
        migrations.CreateModel(
            name='WorkspaceMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='viewer', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_memberships', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.workspace')),
            ],
            options={
                'ordering': ['workspace__name', 'user__username'],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'user'), name='unique_workspace_membership_per_user')],
            },
        ),
        migrations.RunPython(backfill_workspaces, noop_reverse),
    ]
