# Generated by Django 5.2.12 on 2026-03-29 21:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_encrypt_external_repo_connection_tokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviewRunnerSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preview_id', models.UUIDField(db_index=True, unique=True)),
                ('analysis_id', models.UUIDField()),
                ('project_name', models.CharField(max_length=255)),
                ('bundle_url', models.URLField()),
                ('bundle_sha256', models.CharField(max_length=64)),
                ('requested_ttl_seconds', models.PositiveIntegerField(default=1800)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('starting', 'Starting'), ('ready', 'Ready'), ('failed', 'Failed'), ('stopped', 'Stopped'), ('expired', 'Expired')], db_index=True, default='queued', max_length=16)),
                ('runtime_kind', models.CharField(blank=True, choices=[('compose', 'Compose'), ('container', 'Container')], max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('workspace_path', models.CharField(blank=True, max_length=1024)),
                ('workspace_root', models.CharField(blank=True, max_length=1024)),
                ('command', models.CharField(blank=True, max_length=512)),
                ('access_url', models.URLField(blank=True)),
                ('ports', models.JSONField(blank=True, default=dict)),
                ('resource_names', models.JSONField(blank=True, default=list)),
                ('logs', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
